### ISSUE TITLE
Export full grid results not only first page

### ISSUE THREAD

**Issue by devypt** [kartik-v/yii2-grid#204]
When I'm exporting the grid it's only exporting the current page? is there are any configuration to make it export all results.

**Comment by kartik-v** [comment]
Check and read docs for the extension - where you can use (display) the `toggleFullData` button that allows you to toggle between - showing full grid data or paginated data (try [using this button on the demo page](http://demos.krajee.com/grid-demo).

**Comment by jmisasa** [comment]
On the demo page it is probably fine since there are only 20 items but we have about 50k rows we want to export. Is there a simple workaround for this?

Thanks

**Comment by kartik-v** [comment]
The extension has been built to only export data displayed on the client.

You need to write your own query/code for exportinglarge data sets.

**Comment by jmisasa** [comment]
Thank you for your quick answer and keep up the good job!

**Comment by kartik-v** [comment]
An alternative is to use the [yii2-export](http://demos.krajee.com/export) extension which uses PHP Excel library to export and directly reads data from dataProvider. 

But exporting very large data-sets typically are done faster via direct queries rather than too much processing done to change to other formats.

**Comment by jmisasa** [comment]
Thanks again! Will definitely check out those libraries.
