### ISSUE TITLE
DataColumn and other column width property not working

### ISSUE THREAD

**Issue by JamesBarnsley** [kartik-v/yii2-grid#213]
When I use the width property on a DataColumn or any type of column it is not working. Nothing changes or happens.

**Comment by kartik-v** [comment]
I am noting an enhancement to set `persistResize` default to `false` - so that developers can explicitly set it for their scenarios.

**Comment by JamesBarnsley** [comment]
You are correct about the caching, works perfectly now.
Your plugins are amazing by the way, keep up the good work!

**Comment by rtwent** [comment]
Hi, thank You very much for Your extensions.
I am not sure, that it is a bug, but in my case Your answer does not help me. I have the table, the width of which is more then 100% of screen resolution, with parameter: responsive set to true. The table container "table-responsive kv-grid-container" has such style:
.table-responsive {
    min-height: 0.01%;
    overflow-x: auto;
}
The default behaviour for browsers to handle td, th elements of tables is 
"display: table-cell"
but when it is so, the width parameter will not be respected. See http://stackoverflow.com/questions/14765817/why-does-css-td-width-not-work
I decided my problem by setting min-width for td manually by using
[...
'contentOptions'=>['class'=>'td-mw-45']
...]
I think that is not a good decision. But I was unable to find another best in \yii\grid\DataColumn. There is no class members to rule the style of cell. I think it will be useful like callback function in configuration. For example: to make the cell background red, if the cell content is more then 100 etc.

**Comment by kartik-v** [comment]
This response was for issue raised by @JamesBarnsley.

You have other queries & inferences that I am not able to clearly understand OR why you think so. So I will just try to state a few things based on what I can make out:

On responsive tables... this is a bootstrap css feature. [Read about it](http://getbootstrap.com/css/#tables-responsive). It allows you to automatically scroll horizontally if the table width exceeds the parent container width.

If you wish to set column width - this extension directly allows you to set the `width` property which automatically sets the CSS style for header, body, page-summary, and footer. Else you can set it through `contentOptions`, `headerOptions`, and `footerOptions` available with yii core GridView datacolumn (since this extension extends the yii core gridview datacolumn).

**Comment by kartik-v** [comment]
This response was for issue raised by @JamesBarnsley.

You have other queries & inferences that I am not able to clearly understand OR why you think so. So I will just try to state a few things based on what I can make out:

On responsive tables... this is a bootstrap css feature. [Read about it](http://getbootstrap.com/css/#tables-responsive). It allows you to automatically scroll horizontally if the table width exceeds the parent container width.

If you wish to set column width - this extension directly allows you to set the `width` property which automatically sets the CSS style for header, body, page-summary, and footer. Else you can set it through `contentOptions`, `headerOptions`, and `footerOptions` available with yii core GridView datacolumn (since this extension extends the yii core gridview datacolumn). The `contentOptions` can also be set as a Closure callback. Read about these in the yii2 guide.

**Comment by rtwent** [comment]
Thank a lot

**Comment by AlvaroHerrero** [comment]
Thanks for the answer and for your awesome plugins.

**Comment by shamyne** [comment]
I am trying your grid plugin (which looks awesome by the way), but I am having two issues I just cannot figure out.
1.  I cannot resize the grid.  There is no resize handle.  Even when I set the resizableColumns to true, I am still unable to resize the grid.  There are no php or javascript errors.  Everything displays fine, but I  just do not have the resize column functionality. 
2.  I do not want all the text in a cell to display.  I want all the columns to maintain a uniform size and only the content that can fit in that cell size to be displayed.  That is unless the user resizes that column. Is that possible?

Thanks for your help.

**Comment by lkossis** [comment]
Hello,

The width does not work for 

`'format' => 'html'`

where the column content is something like

`<p> ... </p>`
