### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by CristianTan** [kartik-v/yii2-grid#224]
Hello!

How can i use my own translations for grid-view, without having them in your repo? In the debug, i get the following error:

```
The message file for category 'kvgrid' does not exist: C:\wamp\www\kiosk2\vendor\kartik-v\yii2-grid/messages/ro_RO/kvgrid.php Fallback file does not exist as well: C:\wamp\www\kiosk2\vendor\kartik-v\yii2-grid/messages/ro/kvgrid.php
```
Thanks

**Comment by kartik-v** [comment]
Recommended you submit a PR to include in the repo - so that its available for all others who need these translations.

For advanced cases (where you need to use your own translation configuration OR storing it in db)--- you can edit the `i18n` property in the module (refer docs).

**Comment by kartik-v** [comment]
Recommended you submit a PR to include translation message files in the repo - so that it is available for all others who need these translations. If you have a new translation file - do submit this through a pull request.

For advanced cases (where you need to use your own translation configuration OR storing it in db)--- you can edit the `i18n` property in the module (refer docs).

**Comment by kartik-v** [comment]
The reason for submitting a PR and storing messages for the extension in this repo is to ensure consistency and reduce your maintenance. New messages may be added with future extension upgrades... and you will need to continually edit and manage that in your personal repo if that happens - else you will face errors.

**Comment by CristianTan** [comment]
I will do the PR, like i did for Detail View, but in the next days. Don't really have time for this right now. I had to get rid of the error that I had in the Debug, because i have to show the project.

I'll be back with the PR.

Thanks !
