### ISSUE TITLE
Issue with Select2 filter in multiple tag mode

### ISSUE THREAD

**Issue by angelcoding** [kartik-v/yii2-grid#240]
I can't seem to get the select2 grid filter to work in multiple tag mode.
I have pjax turned on and the following in the column config (simplified for brevity):
```
...
[
    ...
    'filterType'=>GridView::FILTER_SELECT2,
    'filter'=>$codesFilterData, 
    'filterWidgetOptions'=>[
        'pluginOptions'=>['allowClear'=>true],
    ],
    'filterInputOptions'=>[
        'placeholder'=>'Filter by codes', 
        'multiple' => true,
    ],
],
...
```
It all works fine until I try to add a second tag or delete the initial one. The filter just won't allow it.
I'm not sure, but the filters seem to submit via pjax before select2 has had a chance to update the hidden select input (the second tag is never even sent in the pjax request).

Can you reproduce the problem? If so, any ideas on a fix?

**Comment by kartik-v** [comment]
Unfortunately cannot do much because its the yii default grid behavior to submit the filter form via pjax as soon as a filter input changes. The change event is fired once you select a tag in select2 - and hence a situation you are facing which you cannot avoid.

- Easier option is to see if you can do this through another form
- But if you wish to override select2 behavior... you may need to check in select2 plugin forums/docs - but would not recommend this approach.

I would try to create a filter specific multiselect widget when I get time.

**Comment by kartik-v** [comment]
One solution is for you to disable the change event specifically for the select2 input using for example `event.preventDefault()`.

Then you can add a button addon to select2 (check the [Select2 widget addons documentation](http://demos.krajee.com/widget-details/select2#addons) for details). on which you can write a click event to trigger the PJAX reload.

**Comment by angelcoding** [comment]
Thanks for your reply. 
Yeah, I've been looking at preventing the event and using a button addon since I posted the issue. 
Looks like the best way for now.
