### ISSUE TITLE
Editable column: three js file is not appear when the column do not have data

### ISSUE THREAD

**Issue by puppyceceyoyo** [kartik-v/yii2-grid#262]
Hi Kartik,

I am not sure if the Editable column has bug. As in when the Editable column DO NOT have any data for the very first place, there is total 3 js file and 2 css file is not loaded. They are shown as below:

editable.js
editable-pjax.js
bootstrap-popover-x.js
kv-widgets.css
bootstrap-popover-x.css

So, when I add the very first data in the same page, (with pjax reload) then it make the column data appear as malfunctioned button (instead of editable dotted bottom line) and not editable(no popover as in js file missing). 

But after I refresh the whole page, those three js file is there and editable column working just fine. (now the gridview has data).

So, the issue is with the 'blank' gridview do not have those 3 js file and 2 css file loaded.

Thanks.

**Comment by kartik-v** [comment]
The `EditableColumn` assets are loaded only when the GridView detects a column class named EditableColumn in its list of columns. This is done to ensure optimal grid performance so that grid without EditableColumns render faster.

**Comment by kartik-v** [comment]
Its not a bug - but expected with the current code.

The `EditableColumn` assets are loaded only when the GridView detects a column class named EditableColumn in its list of columns. This is done to ensure optimal grid performance so that grid without EditableColumns do not have the overheads of loading these js and assets.

Will try to include an enhancement later. Basically an option to force load such assets for developers who need it via a new property.

**Comment by kartik-v** [comment]
Its not a bug - but expected.

The `EditableColumn` assets are loaded only when the GridView detects a column class named EditableColumn in its list of columns. This is done to ensure optimal grid performance so that grid without EditableColumns do not have the overheads of loading these js and assets.

Will check if any enhancement is possible on this later? But i may suggest you to redesign your code to ensure that if no data found - you have an option to refresh grid page after data is been inserted and available.

**Comment by kartik-v** [comment]
Unfortunately I don't think anything can be done on this. The init method for a data column is never called by yii core grid if you do not have any data or rows on initialization.

My recommendation is for you to handle it using workaround in your code .... if dataProvider count is zero ON init - then show a specific content to refresh the grid page.

**Comment by kartik-v** [comment]
The other simpler option is --- you can disable pjax WHEN initial row count is zero.

Basically set pjax property of GridView to FALSE if dataProvider count is zero... else set pjax to true for other cases.

**Comment by puppyceceyoyo** [comment]
For now, when there is no data in gridview, the gridview show 'No results found.'. Are you mean that to replace it with specific content for each column instead of show 'No results found.' in one whole row only? 

I was did a pjax reload when adding data into the gridview in the same view(page). But, when the gridview is no data at the beginning, even after I add the first data into gridview in the same view(page), I added a code to reload the pjax after added new data everytime, but the Editable Column is not working properly as those js file and css file still missing for the very first data ONLY. 

Is that the only way that I could only Refresh whole grid page when that is the first data been inserted into the gridview?

**Comment by puppyceceyoyo** [comment]
I did pjax reload after add new data successfully:

$.pjax.reload({container: '#pjaxOptionIdHere'});

I tried to set Gridview pjax to false when no dataProvider, and vice versa. But I have no luck.

**Comment by puppyceceyoyo** [comment]
Alright, I have modified my code after pjax reload to do a refresh page if there is only one and first data. It works fine now. : )

**Comment by puppyceceyoyo** [comment]
I have worked around my code to refresh the page even after pjax reload WHEN there is only ONE data(first data).

In my function of addNewData(), I added the codes below after pjax reload after new data added successfully:

<?php                       
     $models = $dataProvider->getModels(); // get dataProvider to check if there is any data

     if( count($models) < 1 || $models == null || !isset($models) )                         
     {
 ?>
         window.location.reload();
 <?php                              
     }                      
 ?>

This is works for me now.

**Comment by maxtorchel** [comment]
im using yiibooster on yii1, and i have the same problem, but found the solution in this issue, maybe it help
