### ISSUE TITLE
Export action not performed

### ISSUE THREAD

**Issue by monghuz** [kartik-v/yii2-grid#28]
I use the following code in my index.php

``` php
<?php
use app\models\Company;
use app\models\Person;

use yii\helpers\ArrayHelper;
use kartik\helpers\Html;
use kartik\grid\GridView;
?>
// columns 
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => $gridColumns,
        'floatHeader'=>true,
        'floatHeaderOptions'=>['scrollingTop'=>'50'],
        'panel' => [
            'heading'=>'<h3 class="panel-title"><i class="glyphicon glyphicon-globe"></i> '.$this->title.'</h3>',
            'before'=>Html::a('<i class="glyphicon glyphicon-plus"></i> '.Yii::t('app', 'Create {modelClass}',
                    ['modelClass' => 'Person',]),
                    ['create'], ['class' => 'btn btn-success']),
        ],
    ]); ?>
```

The panels and the export drop-down button showed as expected. 
Workflow:
1 - Select of the export options
2 - Alert message popped up
3 - Gridview refreshed...
4 - ... but nothing else happened. (nothing saved)

Did I missed something with the configuration, why the exported file didn't start to download?

Thanks in advanced

monghuz

**Comment by amit25490** [comment]
Hi Kartik, I have done same process, always getting below error in PDF export code.

"
PHPExcel_Writer_Exception

Unable to load PDF Rendering library
↵
Caused by: PHPExcel_Writer_Exception

Unable to load PDF Rendering library

in /home/php10/SVN/PMS/vendor/phpoffice/phpexcel/Classes/PHPExcel/Writer/PDF/mPDF.php at line 34
"
Also i have installed mpdf and its there in vendor folder, also i have seen its lataest version 7.X (mpdf) and also path of mpdf is of @vendor/mpdf/mpdf now what can be the problem, please help me out.

Tried since 2 days but cant resolve this issue.
