### ISSUE TITLE
Searchcontroller + Exports = Not functional links inside the export?

### ISSUE THREAD

**Issue by davidscr** [kartik-v/yii2-grid#280]
Hey, I can't figure out how i can fix this. I have a GridView with a Searchcontroller. Everything is working fine, also the exports.

But one thing that is bothering me is the following: When i'm exporting my GridView to Excel/PDF/... the table heads are exported as a link. The Searchfields are not there, only the clickable tableheaders (for sorting).

I hope you understand what i mean. Is there any way around this?

Thanks!

**Comment by kartik-v** [comment]
The filter fields are not exported - because they can break the HTML and formatting of the output in PDF... (not sure why one would want to print the filter inputs).

**Comment by davidscr** [comment]
That's not what I mean. The search input fields will not be exported that's right. But the table header is exported as a hyperlink. 

I'm able to attach some screenshots later when I'm on the computer.

Sent from my android phone

**Comment by fwroman** [comment]
Hey kartik-v  why you don't response my questions?? I really need support, if you only want to help some people not to all, please don't make public releases of your widgets or just public to you friends, I understand you have to answer all people who post issues but I see you're discriminating me I've been writing here since a week but I never receive any response of you to my issues, so if you don't want to answer all people just make your widgets code private, thanks

**Comment by kartik-v** [comment]
@fwroman - I really am not obligated to respond nor can I be forced by anyone to respond. I try to do so whenever I find time to do so. 

I am sharing these extensions at my own will and have made it free and open source to all - without any commitment - not asking anything from anyone NOR am I expecting others. I would love to see some help from others - but its mostly me who tries to build and share this based on my interest. You need to understand that. 

Do understand that I get hundreds of communication each day asking for help or support - many of them asking for training or sample code. I do not have personal time to be answering to all - and try to do to the best of my time.

Generally, in a open-source community you need to have contributions from others to drive build and support. Unfortunately I am doing this all by myself in my spare time without any support. This is not something I am building as a business or occupation, nor am I commercializing this -- all these are based on my own free time. 

Unfortunately there are many folks like you who only want help but do not want to provide help. 

Few of the folks are good enough to at least be polite and patient enough to receive help and few of them do submit enhancements to make these extensions better.

And yes to make sure you understand -- I do NOT know anyone personally on github - I just try to respond randomly based on whatever I get time on - or a few folks who do contribute to see these extensions enhanced.

**Comment by davidscr** [comment]
@kartik-v 

No I have added a screenshot of the point i was talking about.

![unbenannt](https://cloud.githubusercontent.com/assets/11403884/7408250/31d086f4-ef1b-11e4-8c23-fead15821f77.PNG)


As you can see the row headlines are exported as a hyperlink, is there any way around this making it text only?

**Comment by kartik-v** [comment]
Not related to this issue.

This is addressed via #288.

**Comment by fwroman** [comment]
@kartik-v It's all right, I understand that and believe me if I had known how to resolve and help others, I would do it, but I don't have enough knowledge about yii2 and your extensions, I've been using the framework since march barely, even so in this few time I've made at least two contributions, one here: https://github.com/kartik-v/yii2-builder/issues/65 when I helped you to improve the tabular form functionality and another here: https://github.com/kartik-v/yii2-widgets/issues/205#issuecomment-93696478 when someone didn't know how to make depdrop work properly. Anyway, I apologize you I know I was not polite in my last comment but I even sent you a message to your gmail account asking so polite for your help and you didn't answer me neither, so now I know you were very busy and I'm sorry to be impatient. Now I hope to help and contribute more in your forums to improve your extensions, and I thank you a lot to share your awesome extensions and thanks for you answer too. This misunderstanding is now solved
