### ISSUE TITLE
ExpandRowColumn won't execute JavaScript inside returned result

### ISSUE THREAD

**Issue by pappfer** [kartik-v/yii2-grid#350]
Example: I want to use the ExpandRowColumn to load a form which contains a DatePicker. It will successfully load the form and display the DatePicker field, but the JavaScript won't get loaded, so the DatePicker won't come up when I click on the field.

For a workaround I'm using the `kvexprow.loaded` event to make DatePicker work, but I don't really like this solution.
```php 
$('#tasks-grid').on('kvexprow.loaded', function (event, ind, key, extra) {
    $('.date-field').kvDatepicker({
        'format': 'yyyy-mm-dd',
        'autoclose': true
    });
});
```

Is there any way to make JavaScript inside returned result run?

**Comment by kartik-v** [comment]
Seems you are using ajax to render the content for expanded row. 

So what you are asking is technically not possible. The ajax based content only will render plain HTML markup - it will not run any embedded javascript code. This is true for any ajax based rendering. You need to run the javascript code after content is loaded in DOM and that's why ExpandRowColumn provides you the event `kvexprow.loaded` to detect that ajax content has been loaded and then you could trigger any javascript for the loaded content via this event.

**Comment by kartik-v** [comment]
Yii's `renderAjax` method can help render content with javascript in specific scenarios depending on your design.

**Comment by pappfer** [comment]
Using Yii's `renderAjax` works fine. Thank you.
