### ISSUE TITLE
refreshGrid only works once

### ISSUE THREAD

**Issue by macbax** [kartik-v/yii2-grid#370]
I set the refreshGrid to true, and the GridView will only refresh once after I updated data in the EditableColumn, I found some other user have the same problem, please fix if you have time. Tia.

**Comment by Bhoft** [comment]
+1

**Comment by kartik-v** [comment]
Cannot seem to exactly reproduce the issue. Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Are you using this with other plugins?

**Comment by Bhoft** [comment]
I have a gridview with pjax enabled and an editable column. After the submission of the editable column i wanted to refresh the grid. 
I set   `'refreshGrid' => true,` and grid also reloads after the 1st editable column change. But if i change the value of an editable column again the post is done but the refresh of the grid isn't.

This is because in your gridview in your beginPjax function Pjax::begin() function is called and every js which was added in the init (and therefore also initColumns) isn't registered on the view any more. 

So after the first refresh of the grid with an editableColumn the id's of the columns are different. And the refresh js call is completely missing. Because the js was only added in the init part.

To reproduce just have a grid with pjax enabled and an editableColumn and refreshGrid enabled.
(you can output the editable column attribute value additionally to the editablecolumn to verify that the grid was refreshed correctly).
- change the value of an editableColumn, 
- 1st refresh is done.
- change the value again and no refresh of the grid is done.

**Comment by kartik-v** [comment]
Note:

- The identifier used in `kvRefreshEC` is only the grid ID and a random CSS - which should not be affected by change in editable input data.
- The primary key value of each model in the row will always remain same... unless you are updating the primary key via the editable column.

**Comment by kartik-v** [comment]
It looks a [similar problem to the way rows are indexed by the dataProvider](https://github.com/kartik-v/yii2-builder/issues/49#issuecomment-78776480). 

You should try using the indexBy(pkey_value) to generate your query on your dataProvider. 

This is [highlighted in the documentation in the beginning for EditableColumn](http://demos.krajee.com/grid#editable-column).

**Comment by Bhoft** [comment]
Hm i have tried this indexBy in the query, still the same issue.
You have written that in kvRefreshEC the grid id is used that is correct, but the 2nd parameter is the id of the Editable column. 
And this ID is changed each Pjax refresh of the grid (e.g. sorting, searching or refresh after an editable change).

I have added 2 debug outputs to the Editablecolumn
```
to the init function
 $this->_view->registerJs("console.log(['init \$this->_css', '{$this->_css}']);");
to the renderDataCellContent function
$this->_view->registerJs("console.log(['renderDataCellContent \$this->_css', '{$this->_css}']);");
```

e.g. on a normal get request i have these 2 console logs
```
["init $this->_css", "kv-edcol-0e645061"]
["renderDataCellContent $this->_css", "kv-edcol-0e645061"]
```

So the init of the EditableColumn has added a js to the view like:
```
kvRefreshEC('grid_id','kv-edcol-0e645061')
```

If I sort for any column of the grid the grid is refreshed normally via pjax.
And i get only one console log with another css id which is used in the editable columns.
```
 ["renderDataCellContent $this->_css", "kv-edcol-81ade31b"]
```
If i then change an editable value the refreshGrid doesn't work because there is no js added to my page through that pjax request which uses the new editablecolumn id like: 
```
kvRefreshEC('grid_id','kv-edcol-81ade31b')
```
If you add a editable column to a pjax grid yourself and set the refreshgrid parameter to true you would see it yourself that the grid is only refreshed once if the editable change is done after the normal get request or not at all if the grid was refreshed with an pjax request.
Because on Pjax::begin() creates a new instance of the calling class. 
http://www.yiiframework.com/doc-2.0/yii-base-widget.html#begin%28%29-detail

Or in other words everything between the Pjax::begin and Pjax::end is sent back on the request.
But the initColumns is done before (inside the Gridview::init()) so every js which is added in the init sections isn't sent to the browser on Pjax requests.
So the refresh doesn't work because the EditableColumn id is changed every request.

If the refresh js code is moved to the renderDataCellContent function it will work as expected.

**Comment by kartik-v** [comment]
The second parameter is not the Editable Column id --- its a randomly generated unique CSS that is attached to each editable cell for triggering the grid refresh the next time based on the CSS identifier.

The Editable Widget is actually initialized based on the updated ID and this is done within `renderDataCellContent` method and the above unique CSS identifier has nothing to do with Editable Initialization.

But I will push an update for this to be sure the grid is refreshed after EditableColumn refresh.

**Comment by Bhoft** [comment]
But this $this->_css is used in the html code of the EditableColumn in the "class" e.g.
```
<td data-col-seq="7" style="width:9%;" class="kv-align-center kv-align-middle"><div class="kv-edcol-6d9f3ef9 kv-editable" id="poll-0-locked-cont"> ...
```

The problem is not only it doesn't refresh the grid after an EditableColumn change more it doesn't refresh after any Pjax request.

But thanks that you will push an update for this issue ;)

**Comment by kartik-v** [comment]
> it doesn't refresh after any Pjax request.

That should not happen UNLESS you are using your own pjax widget routine. If you use the GridView pjax property to `true` - the editable column will auto refresh...

**Comment by kartik-v** [comment]
> it doesn't refresh after any Pjax request.

That should not happen UNLESS you are using your own pjax widget routine. If you use the GridView pjax property to `true` (this is a special propery available for `kartik\grid\GridView`) - then the editable column will auto refresh...

If you are using your own Pjax Widget- then you need to write your own code to refresh the editable column after pjax complete.

**Comment by Bhoft** [comment]
I am not talking about the EditableColumn which isn't changed after the value has been changed.
I am talking about the whole grid which should refresh after an EditableColumn value/html has been changed.
I don't using any other Pjax Widget just your Gridview with pjax enabled and the EditableColumn with refreshGrid set to true.

I have created a test page where the you can see the Problem.
https://evote.eurescom.eu/test

If you change the value of the last column the value would be correctly saved on the model and the grid will be reloaded if the editable change is done after the normal get request. If its done after an pjax request the grid isn't refreshed the value itself is changed correctly on the pjax request done by the editable column. The correct value could be seen if the page is reloaded after the second editable change or after the first editable change if there was an pjax refresh before (e.g. column sort).

I have just added those to console log commands to the EditableColumn class as mentioned above.

**Comment by kartik-v** [comment]
Check with the updated code from dev-master and update.

**Comment by Bhoft** [comment]
thanks working perfectly now.

**Comment by martrix78** [comment]
just solved this problem,
I was inside GRIDVIEW widget in widget PJAX
