### ISSUE TITLE
column resize with persistResize and pjax does some column width jumping

### ISSUE THREAD

**Issue by Bhoft** [kartik-v/yii2-grid#377]
Hi I have just updated to the latest GridView dev version and tried out the column resize with persistResize.

If i set a column width and reload the page with the browser reload button the column width is correctly set.

If I sort for the column the grid is updated correctly with pjax e.g. from AtoZ to ZtoA.
But the initial column width of resized columns is wrong (not the resized one) for some seconds and after some time it is corrected.
If I reload the page after the sorting the column width is correct, so this is not an issue that the wrong width is saved for that column.

I tried to show this in a gif, I loaded the page, sorted the column, waited a few seconds, sorted again and waited again a few seconds, and then reload the page (which couldn't be seen in the gif)

![grabilla h12060](https://cloud.githubusercontent.com/assets/1777147/10070888/c0907850-62b5-11e5-8def-df41a5eb14b5.gif)

I have this settings 
```
resizableColumns => true,
persistResize => true,
resizeStorageKey => Yii::$app->user->id . '-' . date("m"),
pjax => true,
```

the problem is the rendered html code e.g. the first column code, where you see that the width is swapping from px to %.
```
html code which is sent by the sever:
<th class="kv-align-center kv-align-middle skip-export" style="width:80px;" data-resizable-column-id="kv-col-0" data-col-seq="0">Actions</th>

html code after js have been executed:
<th class="kv-align-center kv-align-middle skip-export" style="width: 22.63%;" data-resizable-column-id="kv-col-0" data-col-seq="0">Actions</th>

html code which is returned in the pjax request:
<th class="kv-align-center kv-align-middle skip-export" style="width:80px;" data-resizable-column-id="kv-col-0" data-col-seq="0">Actions</th>

html code after some seconds where the resize done:
<th class="kv-align-center kv-align-middle skip-export" style="width: 22.63%;" data-resizable-column-id="kv-col-0" data-col-seq="0">Actions</th>
```

Couldn't the correct HTML code be generated directly instead of doing the resize after the requests. 
In normal get requests the re-sizing seems to be done before displaying (at least in FF in chrome i see some jumping). But in Pjax requests this column width jumping is more visible.

I had a similar feature (persistent column resize) in some other grid which I used in yii1. Where is had a called an Ajax request each column resize to store the grid columns width in a also persistent user session and could use those widths when i rendered the grid HTML code.

**Comment by kartik-v** [comment]
Note that with `persistResize` the `resizableColumns` plugin will 

- store your previously chosen column widths within localStorage
- it will change your default width setting to the stored value in localStorage

Since this is done at a javascript level - it is expected and it will happen after your page and your default grid is rendered. So it will first show the initial column widths that you have set within GridView column settings.

Then after render - the resizableColumns plugin will override these widths and each user/client will see what they set. 

If you need this to be different - then you need to use Database Storage or similar to store the resized widths and change the widths on INIT at server code level within GridView.
