### ISSUE TITLE
Editable Column : Issue when showing two GridViews in a single view.

### ISSUE THREAD

**Issue by milushinde** [kartik-v/yii2-grid#535]
I am using kartik editable grid view and I am showing 2 GridViews of same model on one single page. Now the issue is that when I click on editable column of second GridView then it is showing and updating data of first GridView's editable column.

Please Help For these issue......
![gv](https://cloud.githubusercontent.com/assets/18546962/17077328/1c78f174-50ea-11e6-9569-566a8890006e.png)

**Comment by kartik-v** [comment]
It is obvious coding issue from your end. You need to write your own code to ensure unique HTML identifiers for the widget markup, inputs, and filters if you are using the same model and attributes to generate widgets on the same page and multiple grid views (since Yii by default generates the HTML identifiers based on model and attribute)

**Comment by milushinde** [comment]
Yes I had fixed it.

**Comment by m-merola** [comment]
Hi, how to change identifiers ?
