### ISSUE TITLE
How to skip requiring mpdf 2

### ISSUE THREAD

**Issue by uldisn** [kartik-v/yii2-grid#572]
Some time ago you this problem solved, but currently it back!

**Comment by kartik-v** [comment]
Follow as the instruction in the exception says:

- Either set `export` to `false` (if you are not using GridView export) - OR
- Do not include the `GridView::PDF` key setting in`export` configuration

**Comment by uldisn** [comment]
Thanks!
 It`s work.

**Comment by schmunk42** [comment]
The secondary solution

```
 'export' => [
        GridView::HTML => [],
        GridView::CSV => [],
        // do not include PDF
    ]
```

does not work for me, I still get the Exception.

What works is:

```
exportConfig' => [
                GridView::HTML => [],
                GridView::CSV => [],
                // do not include PDF
            ],
```

**Comment by kartik-v** [comment]
Yes that is correct.

**Comment by schmunk42** [comment]
It's good that there's a way to disable PDF export, but what I am still saying, also in regard of the other issue, is that everyone who is using `kartik\grid\GridView` without a hand-made config or special composer requirements is getting an exception.

Just my 2 cents.

**Comment by kartik-v** [comment]
Could you mention what is the expectation here and what is to be improved?

The exception will be received  by anyone who does not have yii2-mpdf installed but still trying to use PDF export functionality of yii2-grid.

**Comment by schmunk42** [comment]
> The exception will be received by anyone who does not have yii2-mpdf installed in his/her app but is still trying to use PDF export functionality of yii2-grid.

Which is the default, if you do not "unconfigure" the PDF export.

**Comment by acorncom** [comment]
@kartik-v I believe @schmunk42 is suggesting that pdf export be turned off by default with a note to people who are interested in enabling it that they will need to do so.  That way all other users by default don't run into this issue.  It would be a breaking change though ...

**Comment by kartik-v** [comment]
Will need to evaluate this based on feedback from the majority of the community. Currently the way its designed, most extended functionalities of the extension are enabled by default until its disabled by configuration. 

The only difference being PDF dependency to mPDF library was earlier included in composer.json earlier - but because of the feedback that it may not be needed - it was eliminated from the composer.json with the option of user installing it on his own if needed OR disable PDF. 

There is an exception message generated if PDF functionality is tried to be accessed without mPDF and I suppose its more a documentation pre-requisite now for devs to disable it if not needed using the options above.

Will await more feedback and then take a call to update this.

**Comment by SamMousa** [comment]
How about this solution @kartik-v 
1. Add the mpdf to the recommends of grid.
2. By default enable pdf export if mpdf is available and disable it otherwise.
3. Make sure explicit configuration always overrides the default (so if I explicitly enable pdf export I should get exceptions).

**Comment by kartik-v** [comment]
@SamMousa good suggestions... 

will think on these.

**Comment by SamMousa** [comment]
@kartik-v I can create a PR if you want this improvement; it will not break backwards compatiblity in any working setup. (It will break BC for people that currently get exceptions for missing dependencies).

**Comment by kartik-v** [comment]
Sure you can submit a PR.
