### ISSUE TITLE
Group sum for currency column

### ISSUE THREAD

**Issue by cluwong** [kartik-v/yii2-grid#606]
I need to display total of a column by group.
The group total is displayed correctly when 'format' => ['decimal', 2]. However when changed to 
'format' => 'currency', the group total is blank.
Total in Page Summary field is correct when format is currency.

**Comment by kartik-v** [comment]
Entire grid grouping and group summing is done via javascript and one cannot use Yii formatter options there... 

You can override the default javascript group summing by either setting `groupFooter` as a Closure to use yii formatter or by setting a javascript callback within`groupFooter['contentFormats']`.

**Comment by cluwong** [comment]
It seems to make more sense to have Group total to be automatically inherited the DataColumn setting just like Page Summary do.
Ok, will try the javascript callback.

**Comment by kartik-v** [comment]
> It seems to make more sense to have Group total to be automatically inherited the DataColumn setting just like Page Summary do.

It is not possible because as mentioned earlier, the GRID GROUPING and GROUP SUMMARY are all rendered dynamically at runtime via javascript... and does not rely on PHP code. The JS code has no means to do formatting similar to Yii APP Formatter.

As I mentioned the other option is to  write your own PHP code as a closure to render the group summary.
