### ISSUE TITLE
Export action within form

### ISSUE THREAD

**Issue by wcoc** [kartik-v/yii2-grid#667]
I have problems using the 'export' action of gridview when I need to use the gridview inside a <form>
Whenever I use the grid inside a form the action 'export' becomes a 'textbox', the problem happens due to the form of the export being inside the other form ends up breaking the completion of the other form.

Follow example:
`<?php $form = ActiveForm::begin(['enableClientValidation' => false]); ?> `
`<?= GridView::widget([
                                'id' => 'id-my-table',
                                'pjax'=>true,
                                    '{export}',
                                    '{toggleData}'
                                ],
...`
`<?= Html::submitButton('Send', ['class' => 'btn btn-success' ]) ?>`
`<?php ActiveForm::end(); ?>`

![gridview export into view](https://user-images.githubusercontent.com/7528360/28115840-df7509d4-66dc-11e7-8361-0d8b40dfd46d.png)

**Comment by kartik-v** [comment]
Yes this is expected and you should be writing your code and configuring accordingly. You must not render the grid view within a form - because the grid view itself has its own forms (like the filter form - which is yii default functionality and the export form which is this yii2-grid extension's functionality).

So you need to write your code accordingly to avoid nesting of HTML forms and avoid rendering your markup as INVALID.
