### ISSUE TITLE
Delete action: how to use the same confirm default dialogs with my custom code

### ISSUE THREAD

**Issue by rizrob66** [kartik-v/yii2-grid#681]
Hi Kartik,
probably is a simple problem but I have not found anything about it.
If I do not rewrite the action delete I see the default dialog for confirmation that is the same in detail view. When i rewrite delete action i only found this way to have the confirmation but the dialog box is different.
Is there a way to have the same dialog box even when I rewrite the delete action?
Here is my code for delete action:
`
'delete' => function ($url, $model) {
                    	$url = Yii::$app->urlManager->createUrl(['tab-elezioni/delete', 'id' => $model->id]);
						$icon = '<i class="glyphicon glyphicon-trash"></i>';
						$title = Yii::t('yii', 'Delete');
                        return Html::a($icon, $url,
                            ['title' => $title, 'data-method'=>'post', 
                            'data-confirm' => Yii::t('yii', 'Sei sicuro di voler eliminare questo elemento?'),
                            'data-pjax'=>0] );
		            },
`
Thanks for your help
Roberto

**Comment by kartik-v** [comment]
I will add an enhancement to yii2-dialog to do this better.

**Comment by rizrob66** [comment]
Thanks, you're the best! Please tell my when you done :-)

**Comment by kartik-v** [comment]
There are enhancements done to both `yii2-dialog` (release 1.0.2) and `yii2-grid` (release 3.1.6).

Now the default `data-confirm` attribute for the link or button will automatically render Krajee Dialog styled confirmation prompt.

Secondly I feel you need not entirely overwrite the button action. For example for the delete button, you can override a lot of the common properties like title, label, icon, and the confirmation message shown etc.. by setting `deleteOptions` for the ActionColumn... instead of entirely creating your own new button template action.
