### ISSUE TITLE
EditableColumn does not support dot-based attribute notation

### ISSUE THREAD

**Issue by vercotux** [kartik-v/yii2-grid#735]
This issue is about EditableColumn and Editable.

The column attribute name could be `"foo.bar"` (meaning we are rendering `$model->foo->bar`).

Stock Yii2 DataColumn [supports dot-based attributes](https://github.com/yiisoft/yii2/blob/b20d2692a1c16ea1a8d714b31d0a336649b89238/framework/grid/DataColumn.php#L226), it would make sense if EditableColumn did it too to remain consistent with its parent.

**Comment by kartik-v** [comment]
It would not be trivial or directly possible to implement above - because editable column automatically renders the ActiveForm and ActiveFields in a form... which cannot be possible for related models. If you have a suggestion to improve let know - as of now it is not simple to implement. You can easily manage it by rendering your own additional markup in the content before and after.
